### ISSUE TITLE
Strange looking status notification

### ISSUE THREAD

**Issue by cyn1c** [jaystrictor/gnome-shell-extension-syncthing#12]
First of all, the addition of the status information is an great thing, thanks for that.
I use the extensions on two systems right now, on one it looks exactly the same as it looks in the screenshot on the gnome extensions page. On my laptop (running Antergos Linux) there is no such beautiful looking sync symbol next to the syncthing icon, just a bar as you can see in the screenshot i add to this issue report. 
Is this a known problem which could be fixed? 
![screenshot](https://cloud.githubusercontent.com/assets/11885478/14058669/e7a5a426-f327-11e5-9e3e-26a87bffc48d.png)

**Comment by jaystrictor** [comment]
Thanks for the feedback.

Currently, the sync symbols are not stored as images. Instead they are just some unicode characters. I assume your Antergos system doesn't know how to render these characters, maybe because it lacks a certain font.
In the long run, I want to replace the unicode characters by a proper SVG logo. However, I am not a logo designer, so any help is appreciated.

Could you check on both of your systems, whether you can see the [characters in the source code](https://github.com/jaystrictor/gnome-shell-extension-syncthing/blob/d87478239dfadb56939db9fa327b02ee285eaed8/extension.js#L497-L508)?
Maybe you could even post a screenshot of that link?

**Comment by cyn1c** [comment]
You are right. One the Antergos system the symbol is not shown correctly, while the other system has no problem showing the character. 
![bildschirmfoto von 2016-03-26 12-31-35](https://cloud.githubusercontent.com/assets/11885478/14059820/9a83cbaa-f34f-11e5-8b36-73ed73e9425f.png)
The symbola font was missing on the Antergos system. After installing the font everything looks good!

**Comment by jaystrictor** [comment]
Ok, good that it works for you.
Still... I would like for it to work out of the box on every system. But I guess this can only be achieved if the unicode characters are replaced by proper SVG logos.

**Comment by cyn1c** [comment]
I guess you are right. To bad i'm terrible at everything involving creating graphics. Maybe you could use the current svg and make different colored versions for every status?

**Comment by jaystrictor** [comment]
There are already some discussion going on in a [pull request](https://github.com/syncthing/syncthing/pull/2622). I hope this extension can profit from that some day.

**Comment by jaystrictor** [comment]
We should extract some SVG glyphs from a free font and include them in `/icons`, as @KopfKrieg suggests in PR #15 .

**Comment by KopfKrieg** [comment]
Wow, that was fast! The icons are fine, the extensions is working great so far. Just two little things:

First, the "pause" icon is a little bit too big (in width, not in height) in my opinion (and maybe there should be a space between the syncthing and the pause icon). Here's what I mean:
![extension](https://cloud.githubusercontent.com/assets/5047813/14581612/62723abe-03f1-11e6-9882-28665071f96b.png)

And second, the icons could be a little bit darker. But maybe that's just on my system, because I've enabled the global dark theme.

Everything else: Perfect!

**Comment by jaystrictor** [comment]
You can change the size of the symbols and the space between both of them in the file `stylesheet.css`.
Currently it is set as `icon-size: 0.75em` and `padding-left: 2px`.
What values do you propose?

**Comment by KopfKrieg** [comment]
Hm, good question. The icon-size is fine (In my previous post I meant the pause icon per se, not its size). For the padding-left, maybe about 6px? Looks a bit more separated.
