### ISSUE TITLE
Syncthing Icon displays warning triangle (!) when using TLS=true

### ISSUE THREAD

**Issue by toddco** [jaystrictor/gnome-shell-extension-syncthing#21]
![screenshot from 2016-08-08 11-49-48crop](https://cloud.githubusercontent.com/assets/20910959/17492293/60e82a66-5d68-11e6-8e25-af9d15653e8e.png)

Here is the output of my systemctl query. Looks like i do have it loaded as a user service. The problem is the icon only shows the triangle! next to it and no sync folders are shown. Syncthing button is shown as on (running). Attached a screenshot.

System is manjaro gnome3 64bit, Gnome version 3.20.2

~$ systemctl --user status syncthing.service
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
Loaded: loaded (/usr/lib/systemd/user/syncthing.service; enabled; vendor preset: enabled)
Active: active (running) since Mon 2016-08-08 11:15:22 MDT; 9min ago
Docs: man:syncthing(1)
Main PID: 904 (syncthing)
CGroup: /user.slice/user-1000.slice/user@1000.service/syncthing.service
└─904 /usr/bin/syncthing -no-browser -no-restart -logflags=0

Here is the output from journalctl /usr/bin/gnome-shell -e

[root@asrock-desk todd]# journalctl /usr/bin/gnome-shell -e
Aug 08 12:51:09 asrock-desk org.gnome.Shell.desktop[986]: Gjs-Message: JS LOG: Failed to connect to syncthing daemon at URI 'https://192.168.1.4:7070': 6 Unacceptable TLS certificate
Aug 08 12:51:19 asrock-desk org.gnome.Shell.desktop[986]: Gjs-Message: JS LOG: Failed to connect to syncthing daemon at URI 'https://192.168.1.4:7070': 6 Unacceptable TLS certificate
.......>
Aug 08 12:54:59 asrock-desk org.gnome.Shell.desktop[986]: Gjs-Message: JS LOG: Failed to connect to syncthing daemon at URI 'https://192.168.1.4:7070': 6 Unacceptable TLS certificate
Aug 08 12:55:09 asrock-desk org.gnome.Shell.desktop[986]: Gjs-Message: JS LOG: Failed to connect to syncthing daemon at URI 'https://192.168.1.4:7070': 6 Unacceptable TLS certificate

I have changed the web interface through extensions.gnome.org settings to my nas box. Everything sinks back to that. I can click the web interface icon on the dropdown in Syncthing Icon and it opens the nas interface web page no errors or issues.

Also I am on 0.13 series on all my devices due to the maintainer of syncthing package on my nas is slow to up grade. I thought i understood that 0.13 and 0.14 are not compatible, but dont know if that is relavant.

**Comment by jaystrictor** [comment]
The problem in this case is that TLS is pretty much unsupported by this extension, I'm sorry :(

The syncthing TLS certificates are self-signed, so we need the user to verify them. Currently, in the Gnome javascript interpreter `gjs` there seems to be no tool to do this easily.
I already asked on the [gnome javascript mailing list](https://mail.gnome.org/archives/javascript-list/2016-June/msg00000.html), but as it turns out in `gjs` the Gnome libraries are only partially implemented.

One workaround would be to disable `tls` in `~/.config/syncthing/config.xml`, disabling encryption for the web interface. For a web interface listening only on `127.0.0.1` this should be ok. I don't know whether it's ok for your setup.
