### ISSUE TITLE
Syncthing icon in state PAUSED after reboot system

### ISSUE THREAD

**Issue by terrakok** [jaystrictor/gnome-shell-extension-syncthing#25]
Syncthing tray icon has PAUSED state after reboot system but syncthing daemon is running and works normally

**Comment by jaystrictor** [comment]
Could you post the output of

    systemctl --user status syncthing.service
    grep tls= ~/.config/syncthing/config.xml

and the relevant lines of

    journalctl -e /usr/bin/gnome-shell

Furthermore, a little screenshot could be helpful.

**Comment by terrakok** [comment]
```bash
terrakok@terrakok-UX31A:~$ systemctl --user status syncthing.service
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
   Loaded: loaded (/usr/lib/systemd/user/syncthing.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:syncthing(1)

terrakok@terrakok-UX31A:~$ grep tls= ~/.config/syncthing/config.xml
    <gui enabled="true" tls="false" debugging="false">
```

![](https://habrastorage.org/files/a83/615/414/a836154140414b60a5568ae6b70140b2.png)

**Comment by jaystrictor** [comment]
Looks like you have syncthing started from a systemd **system service**.

This extension uses the **user service** management facilities of systemd. The [Syncthing documentation](https://docs.syncthing.net/users/autostart.html#how-to-set-up-a-user-service) has information about how to set this up. Please make sure that you have the user units installed correctly, otherwise the on/off switch will not work.

**Comment by terrakok** [comment]
Yes, you are right! Thx
