### ISSUE TITLE
Add "upload" indication while Syncthing is sending data to other devices

### ISSUE THREAD

**Issue by njam** [jaystrictor/gnome-shell-extension-syncthing#33]
It would be great if the icon would change while Syncthing is *sending* data to other devices, but the local copy is in-sync. Currently the icon is in state "idle" in that case:
![image](https://user-images.githubusercontent.com/360800/32195116-a839c4be-bdbc-11e7-89d5-c8a0d1b5009c.png)
This way I would know that I still need to wait for the upload to finish before closing my Laptop.

Thanks for this great extension btw!

**Comment by jaystrictor** [comment]
I agree, this would be a nice information.

It has been some time since I have looked into the REST API of syncthing, but as far as I remember, there is no API representation for an "uploading" state in the REST API.
For example in the API call  [`/rest/db/status`](https://docs.syncthing.net/rest/db-status-get.html), the `state` property can only be `idle`, `scanning`, `syncing`, `error`, or `unknown`. See the syncthing source file [`folderstate.go`](https://github.com/syncthing/syncthing/blob/master/lib/model/folderstate.go).

If you have any other idea, how one could detect an uploading folder, please let me know.

**Comment by njam** [comment]
Maybe we could request [`/rest/system/connections`](https://docs.syncthing.net/rest/system-connections-get.html) continuously, and calculate the delta of the previous and the current value for `inBytesTotal` and `outBytesTotal`? The Web GUI client is doing something like this in [`refreshConnectionStats()`](https://github.com/syncthing/syncthing/blob/d65f1fb08a4b4bb41aff64a699af06435750d235/gui/default/syncthing/core/syncthingController.js#L521).
This seems to not only include *file transfer* bandwidth, but also other protocol transfers. But in a quick test it seems to be a pretty good indicator.

**Comment by jaystrictor** [comment]
Interesting.
I would be glad to receive pull requests. :)

**Comment by njam** [comment]
Can you assign this ticket to me?
I will net get to it now, but I would be curious to try when I have more free time!

**Comment by njam** [comment]
Sorry I didn't get around to work on this.
I'm using a different extension now ([Syncthing Indicator by 2nv2u](https://extensions.gnome.org/extension/1070/syncthing-indicator/)), so this is not relevant for me anymore.
